media:
  input: assets/gfx
  output: /gfx/

content:
  - name: posts
    label: Posts
    path: site/articles
    type: collection
    view:
      fields: [ title, date ]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: 'yyyy-MM-dd HH:mm:S'
        