media:
  input: assets/gfx
  output: /gfx/

content:
  - name: posts
    label: Posts
    path: site/articles
    type: collection
    view:
      fields: [ title, date ]
    fields:
      - name: Title
        label: title
        type: string
        