media:
  input: assets/gfx
  output: /gfx/

content:
  - name: posts
    label: Posts
    path: site/articles
    type: collection
    view:
      fields: [ title, date ]
      sort: [ date, title ]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd HH:mm:s
      - name: description
        label: Description
        type: string
      - name: Tags
        label: Description
        type: string
        list: true
      - name: series
        label: Series
        type: string
      - name: publication
        label: Publication
        type: string
      - name: canonical
        label: Canonical URL
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: type
        type: string
        default: articles-item
        hidden: true
      - name: layout
        type: string
        default: default
        hidden: true
        
        