media:
  input: assets/gfx
  output: /gfx/

content:
  - name: posts
    label: Posts
    path: site/articles
    type: collection
    view:
      fields: [ title, date ]
      sort: [ date, title ]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd HH:mm:ss
      - name: description
        label: Description
        type: string
      - name: tags
        label: Tags
        type: string
        list: true
      - name: body
        label: Body
        type: code
        options:
          language: markdown
      - name: series
        label: Series
        type: string
      - name: publication
        label: Publication
        type: string
      - name: canonical
        label: Canonical URL
        type: string
      - name: project
        label: Project
        type: object
        fields:
          - name: name
            label: Name
            type: string
          - name: href
            label: Href
            type: string
      - name: permalink
        label: Permalink
        type: string
      - name: eleventyExcludeFromCollections
        label: Exclude from collections
        type: string
      - name: type
        type: string
        default: articles-item
        hidden: true
      - name: layout
        type: string
        default: default
        hidden: true
  - name: invalid-css
    label: Invalid CSS
    path: site/side-projects/invalid-css
    type: collection
    exclude: [index.md]
    view:
      fields: [ title, date ]
      sort: [ date, title ]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd HH:mm:ss
      - name: description
        label: Description
        type: string
      - name: tags
        label: Tags
        type: string
        list: true
      - name: body
        label: Body
        type: code
        options:
          language: markdown
      - name: type
        type: string
        default: articles-item
        hidden: true
      - name: layout
        type: string
        default: default
        hidden: true
  - name: web-dev-zoo
    label: Web Dev Zoo
    path: site/side-projects/web-dev-zoo
    type: collection
    exclude: [index.md]
    view:
      fields: [ title, date ]
      sort: [ date, title ]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd HH:mm:ss
      - name: description
        label: Description
        type: string
      - name: tags
        label: Tags
        type: string
        list: true
      - name: og_img
        label: OG image
        type: string
      - name: body
        label: Body
        type: code
        options:
          language: markdown
      - name: type
        type: string
        default: articles-item
        hidden: true
      - name: layout
        type: string
        default: default
        hidden: true