media:
  input: assets/gfx
  output: /gfx/

content:
  - name: posts
    label: Posts
    path: site/articles
    type: collection
    view:
      fields: [ title, date ]
      primary: title
      sort: [ date, title, tags ]
      default:
        search: ''
        sort: date
        order: desc
    fields: