backend:
  name: git-gateway
  branch: staging

media_folder: none

# local_backend: true

collections:
  - label: "Newsletter"
    name: "newsletter"
    folder: "site/side-projects/ui-dev-newsletter"
    slug: "{{year}}-{{month}}-{{day}}"
    create: true
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        required: false
        default: newsletter
      - label: "Type"
        name: "type"
        widget: "hidden"
        required: false
        default: newsletter-single
      - label: "Title"
        name: "title"
        widget: "string"
        required: false
        default: "Issue #"
      - label: "OG Title"
        name: "ogImageTitle"
        widget: "string"
        required: false
        default: "UI Dev Newsletter: Issue #"
      - label: "Date"
        name: "date"
        widget: "date"
        required: false
        format: "YYYY-MM-DD"
      - label: "Description"
        name: "description"
        widget: "string"
        required: false
        default: "In this issue: "
      - label: "List"
        name: "list"
        widget: "list"
        required: false
        summary: "{{fields.title}}"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Link"
            name: "link"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Twitter"
            name: "handle"
            widget: "string"
            required: false
          - label: "Mastodon"
            name: "handle2"
            widget: "string"
            required: false
      - label: "Promotion"
        name: "promotion"
        widget: "list"
        required: false
        summary: "{{fields.title}}"
        fields:
          - label: "Type"
            name: "type"
            widget: "select"
            required: false
            options: ["Twitter thread", "Popular on Twitter", "Popular on CodePen", "Just for fun", "Self-promotion", "Hacktoberfest", "Story", "Around the web", "Discussion", "Word of advice", "Freebie"]
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Link"
            name: "link"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Twitter"
            name: "handle"
            widget: "string"
            required: false
          - label: "Mastodon"
            name: "handle2"
            widget: "string"
            required: false
      - label: Ad
        name: topAd
        widget: object
        required: false
        summary: '{{fields.name}}'
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
            required: false
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Link"
            name: "link"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Twitter"
            name: "handle"
            widget: "string"
            required: false
          - label: "Mastodon"
            name: "handle2"
            widget: "string"
            required: false
